CREATE DATABASE WEBSITE_WITH_BONUSES;
USE WEBSITE_WITH_BONUSES;

CREATE TABLE USERS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD NVARCHAR(255),
    SALT NVARCHAR(255),
    IS_SELLER BIT DEFAULT 0,
    NUMBER_OF_BONUSES INT NOT NULL,
    UNIQUE_CODE NVARCHAR(255) NOT NULL
);

SELECT * FROM USERS;

DELETE FROM USERS;

DROP TABLE USERS;